name: Comment on Closed Issue

on:
  issues:
    types:
      - closed

jobs:
  commentOnClose:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to the closed issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "Thank you for closing this issue! 🎉 If you have more questions, feel free to open a new one."
            });
