name: Comment on Closed Issue

on:
  issues:
    types:
      - closed

permissions:
  issues: write


jobs:
  checkCommentAndReopen:
    runs-on: ubuntu-latest
    steps:
      - name: Check last comment and act accordingly
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.payload.issue.number;

            // Get all comments on the issue
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            // Check the last comment
            const lastComment = comments.data.pop(); // Get the last comment (if any)

            if (lastComment && lastComment.body.trim() === "I am a bad dog.") {
              console.log("Last comment matches the specific form. No action needed.");
            } else {
              console.log("Last comment does not match or no comments exist. Adding a new comment and reopening the issue.");

              // Add a new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: "I am a bad dog.",
              });

              // Reopen the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: "open",
              });
            }
